routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','FrontController@index');

Route::get('/perfil/{nombre}', [

	'uses' => 'FrontController@perfil',

	'as' => 'usuario.perfil'


	]);

Route::put('/perfil/{nombre}', [

	'uses' => 'FrontController@perfil_update',

	'as' => 'usuario.update'

	]);

Route::get('/cursos','FrontController@cursos');

Route::group(['prefix' => 'cursos'], function () {

Route::get('/categorias/{nombre}',[


	'uses' => 'FrontController@buscarCategoria', 
	'as' => 'buscar.categoria'

	]);

Route::get('/autor/{name}',[

	'uses' => 'FrontController@buscarAutores',
	'as' => 'buscar.autores'


	]);



});


Route::get('/cursos/{slug}',[

	'uses' => 'FrontController@contenido',
	'as' => 'curso.contenido'

	]);

Route::get('/politicas','FrontController@politicas');

Route::get('/terminos','FrontController@terminos');



Auth::routes();


Route::get('/home', 'HomeController@index');

//RUTAS DE ADMINISTRADOR

Route::group(['prefix' => 'administrador', 'middleware' => 'auth'], function () {

//-->AQUI SE PUEDEN COLOCAR RUTAS DE ACCCESO ADMINISTRATIVO PARA USUARIOS MIEMBRO

	Route::group(['middleware'=>'administrador'], function() {

					Route::resource('usuarios','UsuariosController');

					Route::get('/usuarios/{id}/destroy',[

						'uses' => 'UsuariosController@destroy',
						'as'   => 'administrador.usuarios.destroy'

						]);
					Route::resource('categorias','CategoriasController');

					Route::get('/categorias/{id}/destroy',[

						'uses' => 'CategoriasController@destroy',
						'as'   => 'administrador.categorias.destroy'

						]);

					Route::resource('tags','TagsController');

					Route::get('/tags/{id}/destroy',[

						'uses' => 'TagsController@destroy',
						'as'   => 'administrador.tags.destroy'

						]);

					Route::resource('/cursos','CursosController');

					Route::get('/cursos/{id}/destroy',[

						'uses' => 'CursosController@destroy',
						'as'   => 'administrador.cursos.destroy'

						]);

					Route::get('/imagenes',[

						'uses' => 'ImagenesController@index',
						'as'   => 'administrador.imagenes.index'

						]);

			Route::group(['prefix' => 'curso/{id_curso}'], function () {

					Route::resource('/contenidos','ContenidosController');

					Route::get('/contenidos/{id_contenido}/destroy',[

						'uses' => 'ContenidosController@destroy',
						'as'   => 'administrador.contenidos.destroy'

						]);

								Route::group(['prefix' => 'contenido/{id_contenido}'], function () {

											Route::resource('/capitulos','CapitulosController');

											Route::get('/capitulos/{id_capitulo}/destroy',[

											'uses' => 'CapitulosController@destroy',
											'as'   => 'administrador.capitulos.destroy'

									]);

				});

				});

	});



});

app/Curso.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use App\Categoria;

class Curso extends Model
{

    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'nombre'
            ]
        ];
    }

       public static function findBySlugOrFail($slug, array $columns = ['*']){
        return static::whereSlug($slug)->firstOrFail($columns);
    }


    protected $table = "cursos";
    protected $fillable = ['nombre','descripcion','type','user_id','category_id','autor_id','slug'];

 

    public function categoria() {

    	return $this->belongsTo('App\Categoria','category_id');
    }

    public function user() {

    	return $this->belongsTo('App\User');
    }

        public function autor() {

        return $this->belongsTo('App\Autor');
    }

    public function imagenes() {

    	return $this->hasMany('App\Imagen');
    }

    public function tags() {

    	return $this->belongsToMany('App\Tag');
    }

        public function contenidos () {

        return $this->hasMany('App\Contenido','curso_id');
    }

       public function capitulos (){

        return $this->hasMany('App\Capitulo');
    }


        public function scopeBuscador($query ,$nombre) {

        return $query->where('nombre', 'LIKE', "%$nombre%");

    }

             public function scopeBuscarDestacados($query) {

        return $query->where('type', '=', "destacado");

     }
}

app/Http/Controllers/CursosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categoria;
use App\Autor;
use App\Tag;
use App\Curso;
use App\Imagen;
use Laracasts\Flash\Flash;
use App\User;
use App\Http\Requests\CursoRequest;

class CursosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $cursos = Curso::buscador($request->nombre)->orderBy('id','DESC')->paginate(10);

        $cursos->each(function($cursos){

            $cursos->categoria;
            $cursos->user;

        });

        

        return view('administrador.cursos.index',['cursos' => $cursos]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = Categoria::orderBy('nombre','ASC')->pluck('nombre','id');
         $autores = Autor::all()->pluck('nombre','id');
        $tags = Tag::orderBy('nombre','ASC')->pluck('nombre','id');
        //dd($categorias);
        return view('administrador.cursos.create',['categorias' => $categorias,  'autores' => $autores ,'tags' => $tags]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CursoRequest $request)
    {
        $hasfile = $request->hasFile('imagen') && $request->imagen->isValid();
        
        if( $hasfile){

            $curso  = new Curso($request->all());
            $curso->user_id = \Auth::user()->id;
            
               if($curso->save()) {
                
                $curso->tags()->sync($request->tags);

                $file = $request->file('imagen');
                $extension = $request->imagen->extension();
                $nombre_imagen = str_slug($curso->nombre) . "-" . time() . "." .$extension;

                $imagen = new Imagen();
                $imagen->nombre = $nombre_imagen;
                $imagen->curso()->associate($curso);

                       if($imagen->save()) {

                            $ruta = public_path() . '/images/cursos';
                            $file->move($ruta,$nombre_imagen);   
                       
                       }else{
                        Flash::error("No se pudo guardar la Imagen , Intentelo de nuevo");
                        return redirect()->route('cursos.create');
                       }

                Flash::success("Se ha registrado el curso: ". $curso->nombre . " Exitosamente¡¡");
                return redirect()->route('cursos.index');    
               
               }else{
                Flash::error("No se pudo crear el curso");
                return redirect()->route('cursos.create');
               }

    
        } else {

                Flash::error("Error al cargar la Imagen, Intentelo nuevamente");
                return redirect()->route('cursos.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $curso = Curso::find($id);
        $curso->categoria;

       $categorias = Categoria::orderBy('nombre','DESC')->pluck('nombre','id');
       $autores = Autor::all()->pluck('nombre','id');
       $tags = Tag::orderBy('nombre','DESC')->pluck('nombre','id');
       $my_tags = $curso->tags->pluck('id')->ToArray();



       return view('administrador.cursos.edit',['curso' => $curso, 'categorias' => $categorias, 'autores' => $autores ,'tags' => $tags, 'my_tags' => $my_tags]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $curso = Curso::find($id);
        $curso->fill($request->all());

         if($curso->save()) {

        $curso->tags()->sync($request->tags);

        Flash::success("Se ha actualizado el curso : ". $curso->nombre . " Exitosamente¡¡");
        return redirect()->route('cursos.index');   
       
       }else{
        Flash::error("No se pudo actualizar el curso");
        return redirect()->route('cursos.edit',$id);
       }

        


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $curso = Curso::find($id);
        
        if($curso->delete()) {

        Flash::success("Usuario: " . $curso->nombre . " Eliminado Exitosamente¡¡");
        return redirect()->route('cursos.index');   
       
       }else{
        Flash::error('No se pudo eliminar el curso');
        return redirect()->route('cursos.index'); 
       }
    }
}

resources/views/administrador/cursos/create.blade.php
@extends('layouts.app')

@section('title','Crear Curso')

@section('css')
<link href="{{ url('plugins/chosen/chosen.css') }}" rel="stylesheet">
<link href="{{ url('plugins/trumbowyg/dist/ui/trumbowyg.css') }}" rel="stylesheet">
@endsection

@section('header')

@include('partials.header')

@endsection

@section('content')

<div class="view-school">

		<section id="breadcrumbs-container">
			<div class="container">
				<div class="row">
					<div class="col-xs">
						<nav class="breadcrumb">

							<a href="{{route('cursos.index')}}" class="breadcrumb-item">Cursos</a>
							<span class="breadcrumb-item active">/ Creacion de cursos</span>
						</nav>
					</div>
				</div>
			</div>
		</section>

<div class="admin-panel">

<h4>Crear nuevo curso</h4>

{!!Form::open(['route' => 'cursos.store', 'method' => 'POST', 'files'=> true])!!}

<div class="form-group">
	{!!Form::label('nombre','Nombre del Curso')!!}
	{!!Form::text('nombre', null, ['class' => 'form-control', 'placeholder'=> 'Nombre del curso' ,'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('category_id','Categoria')!!}
	{!!Form::select('category_id', $categorias, null, ['class' => 'form-control select-category',  'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('descripcion','Descripcion')!!}
	{!!Form::textarea('descripcion', null, ['class' => 'form-control textarea-content', 'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('type','Tipo de Curso')!!}
	{!!Form::select('type', ['normal' => 'Normal','destacado' => 'Destacado'],null,['class' => 'form-control', 'placeholder' => 'Seleccione una opción...', 'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('autor_id','Autor')!!}
	{!!Form::select('autor_id', $autores, null, ['class' => 'form-control select-category',  'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('tags','Tags')!!}
	{!!Form::select('tags[]', $tags, null, ['class' => 'form-control select-tag', 'multiple' ,'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('imagen','Imagen')!!}
	{!!Form::file('imagen')!!}
</div>

<div class="form-group text-center">
	{!!Form::submit('Registrar', ['class' => 'btn btn-primary '])!!}
</div>

{!!Form::close()!!}

</div>

</div>

@endsection

@section('footer')

@include('partials.footer')

@endsection

@section('js')

	<script src="{{ url('plugins/chosen/chosen.jquery.js') }}"></script>
	<script src="{{ url('plugins/trumbowyg/trumbowyg.js') }}"></script>

<script>
	$('.select-tag').chosen({
			placeholder_text_multiple: 'Seleccione un máximo de 3 tags',
			max_selected_options: 3,
			search_contains: true,
			no_results_text: 'No se encontraron tags'
	});

	$('.select-category').chosen();

	$('.textarea-content').trumbowyg();

	
</script>


@endsection

resources/views/administrador/cursos/edit.blade.php
@extends('layouts.app')

@section('title','Editar Curso')

@section('css')
<link href="{{ url('plugins/chosen/chosen.css') }}" rel="stylesheet">
<link href="{{ url('plugins/trumbowyg/dist/ui/trumbowyg.css') }}"  rel="stylesheet" >
@endsection

@section('header')

@include('partials.header')

@endsection

@section('content')


<div class="view-school">

		<section id="breadcrumbs-container">
			<div class="container">
				<div class="row">
					<div class="col-xs">
						<nav class="breadcrumb">

							<a href="{{route('cursos.index')}}" class="breadcrumb-item">Cursos</a>
							<span class="breadcrumb-item active">/ Edicion de cursos</span>
						</nav>
					</div>
				</div>
			</div>
		</section>

<div class="admin-panel">

<h4>Editar Curso: ("{{$curso->nombre}}")</h4>

{!!Form::open(['route' => ['cursos.update', $curso->id], 'method' => 'PUT'])!!}

<div class="form-group">
	{!!Form::label('nombre','Nombre del Curso')!!}
	{!!Form::text('nombre', $curso->nombre, ['class' => 'form-control', 'placeholder'=> 'Titulo del curso' ,'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('category_id','Categoria')!!}
	{!!Form::select('category_id', $categorias, $curso->categoria->id, ['class' => 'form-control select-category',  'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('descripcion','Descripcion')!!}
	{!!Form::textarea('descripcion', $curso->descripcion, ['class' => 'form-control textarea-content', 'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('type','Tipo de Curso')!!}
	{!!Form::select('type', ['normal' => 'Normal','destacado' => 'Destacado'],$curso->type,['class' => 'form-control', 'placeholder' => 'Seleccione una opción...', 'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('autor_id','Autor')!!}
	{!!Form::select('autor_id', $autores, $curso->autor->id, ['class' => 'form-control select-category',  'required'])!!}
</div>

<div class="form-group">
	{!!Form::label('tags','Tags')!!}
	{!!Form::select('tags[]', $tags, $my_tags, ['class' => 'form-control select-tag', 'multiple' ,'required'])!!}
</div>


<div class="form-group text-center">
	{!!Form::submit('Editar curso', ['class' => 'btn btn-primary '])!!}
</div>

{!!Form::close()!!}

</div>
</div>

@endsection

@section('footer')

@include('partials.footer')

@endsection

@section('js')

	<script src="{{ url('plugins/chosen/chosen.jquery.js') }}"></script>
	<script src="{{ url('plugins/trumbowyg/trumbowyg.js') }}"></script>

<script>
	$('.select-tag').chosen({
			placeholder_text_multiple: 'Seleccione un máximo de 3 tags',
			max_selected_options: 3,
			search_contains: true,
			no_results_text: 'No se encontraron tags'
	});

	$('.select-category').chosen();

	$('.textarea-content').trumbowyg();

	
</script>


@endsection

resources/views/administrador/cursos/index.blade.php
@extends('layouts.app')

@section('title','Cursos')

@section('header')

@include('partials.header')

@endsection

@section('content')

<div class="view-school">

		<section id="breadcrumbs-container">
			<div class="container">
				<div class="row">
					<div class="col-xs">
						<nav class="breadcrumb">
							
							<a href="{{route('usuarios.index')}}" class="breadcrumb-item">/ Usuarios</a>
							<a href="{{route('categorias.index')}}" class="breadcrumb-item">/ Categorias</a>
							<span class="breadcrumb-item active">/ Cursos</span>
							<a href="{{route('administrador.imagenes.index')}}" class="breadcrumb-item">/ Imagenes</a>
							<a href="{{route('tags.index')}}" class="breadcrumb-item">/ Tags</a>
							
						</nav>
					</div>
				</div>
			</div>
		</section>

<div class="admin-panel">

<div class="row">
	<div class="col-md-4 col-xs-12">
		<h4>Cursos registrados</h4>
	</div>




 <!-- CAJA DE BUSQUEDAS -->

      {!!Form::open(['route' => 'cursos.index', 'method' => 'GET' , 'class' => 'col-lg-4 col-md-4 col-xs-12 pull-right'])!!}

     
       
            <div class="input-group">

			{!!Form::text('nombre' ,null ,['class' => 'form-control search input-lg', 'placeholder' => 'Buscar Curso'])!!}
			
            <span class="input-group-btn">
            
              <button id="search-course-button" class="btn search btn-default btn-lg" type="submit"><i class='fa fa-search'></i></button>
           
            </span>
          </div>
      
     

      {!!Form::close()!!}

      </div>
    
   <!-- CAJA DE BUSQUEDAS -->

<table class="table table-striped">	
		<thead>
			<th>ID</th>
			<th>Nombre del Curso</th>
			<th>Categoria</th>
			<th>Usuario</th>
			<th>Tipo de Curso</th>
			<th>Accion</th>
		</thead>
		<tbody>
			@foreach($cursos as $curso)
				<tr>
					<td>{{$curso->id}}</td>
					<td><a href="{{route('contenidos.index',[$curso->id])}}">{{$curso->nombre}}</a></td>
					<td>{{$curso->Categoria->nombre}}</td>
					<td>{{$curso->User->name}}</td>
										<td>
						
						@if($curso->type == "normal")
							<span class="label label-primary">{{$curso->type}}</span>
						@else
							<span class="label label-danger">{{$curso->type}}</span>
						@endif


					</td>
					<td>
						<a class="btn btn-warning" href="{{route('cursos.edit',$curso->id)}}"><i class="fa fa-pencil-square" aria-hidden="true"></i></a>
						<a class="btn btn-danger" href="{{route('administrador.cursos.destroy',$curso->id)}}" onclick="return confirm('¿Seguro que deeas Eliminar este usuario')"><i class="fa fa-trash" aria-hidden="true"></i></a>

					</td>

				</tr>
			@endforeach
		</tbody>
</table>

<a class="btn btn-primary" href="{{route('cursos.create')}}">Crear nuevo curso</a>

<div class="text-center" >{!!$cursos->links()!!}</div>


</div>
</div>

@endsection

@section('footer')

@include('partials.footer')

@endsection