routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','FrontController@index');

Route::get('/perfil/{nombre}', [

	'uses' => 'FrontController@perfil',

	'as' => 'usuario.perfil'


	]);

Route::put('/perfil/{nombre}', [

	'uses' => 'FrontController@perfil_update',

	'as' => 'usuario.update'

	]);

Route::get('/cursos','FrontController@cursos');

Route::group(['prefix' => 'cursos'], function () {

Route::get('/categorias/{nombre}',[


	'uses' => 'FrontController@buscarCategoria', 
	'as' => 'buscar.categoria'

	]);

Route::get('/autor/{name}',[

	'uses' => 'FrontController@buscarAutores',
	'as' => 'buscar.autores'


	]);



});


Route::get('/cursos/{slug}',[

	'uses' => 'FrontController@contenido',
	'as' => 'curso.contenido'

	]);

Route::get('/politicas','FrontController@politicas');

Route::get('/terminos','FrontController@terminos');



Auth::routes();


Route::get('/home', 'HomeController@index');

//RUTAS DE ADMINISTRADOR

Route::group(['prefix' => 'administrador', 'middleware' => 'auth'], function () {

//-->AQUI SE PUEDEN COLOCAR RUTAS DE ACCCESO ADMINISTRATIVO PARA USUARIOS MIEMBRO

	Route::group(['middleware'=>'administrador'], function() {

					Route::resource('usuarios','UsuariosController');

					Route::get('/usuarios/{id}/destroy',[

						'uses' => 'UsuariosController@destroy',
						'as'   => 'administrador.usuarios.destroy'

						]);
					Route::resource('categorias','CategoriasController');

					Route::get('/categorias/{id}/destroy',[

						'uses' => 'CategoriasController@destroy',
						'as'   => 'administrador.categorias.destroy'

						]);

					Route::resource('tags','TagsController');

					Route::get('/tags/{id}/destroy',[

						'uses' => 'TagsController@destroy',
						'as'   => 'administrador.tags.destroy'

						]);

					Route::resource('/cursos','CursosController');

					Route::get('/cursos/{id}/destroy',[

						'uses' => 'CursosController@destroy',
						'as'   => 'administrador.cursos.destroy'

						]);

					Route::get('/imagenes',[

						'uses' => 'ImagenesController@index',
						'as'   => 'administrador.imagenes.index'

						]);

			Route::group(['prefix' => 'curso/{id_curso}'], function () {

					Route::resource('/contenidos','ContenidosController');

					Route::get('/contenidos/{id_contenido}/destroy',[

						'uses' => 'ContenidosController@destroy',
						'as'   => 'administrador.contenidos.destroy'

						]);

								Route::group(['prefix' => 'contenido/{id_contenido}'], function () {

											Route::resource('/capitulos','CapitulosController');

											Route::get('/capitulos/{id_capitulo}/destroy',[

											'uses' => 'CapitulosController@destroy',
											'as'   => 'administrador.capitulos.destroy'

									]);

				});

				});

	});



});

app/Http/Controllers/ImagenesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Imagen;

class ImagenesController extends Controller
{
   public function index(){

   	$imagenes = Imagen::orderBy('id','DESC')->simplepaginate(6);

   	$imagenes->each(function ($imagenes){
   		$imagenes->curso;
   	});
   	

   	return view('administrador.imagenes.index',['imagenes' => $imagenes]);

   }
}

resources/views/administrador/imagenes/index.blade.php
@extends('layouts.app')

@section('title','Imagenes')

@section('header')

@include('partials.header')

@endsection

@section('content')

<div class="view-school">

		<section id="breadcrumbs-container">
			<div class="container">
				<div class="row">
					<div class="col-xs">
						<nav class="breadcrumb">
							
							<a href="{{route('usuarios.index')}}" class="breadcrumb-item">/ Usuarios</a>
							<a href="{{route('categorias.index')}}" class="breadcrumb-item">/ Categorias</a>
							<a href="{{route('cursos.index')}}" class="breadcrumb-item">/ Cursos</a>
							<span class="breadcrumb-item active">/ Imagenes</span>
							<a href="{{route('tags.index')}}" class="breadcrumb-item">/ Tags</a>
							
						</nav>
					</div>
				</div>
			</div>
		</section>

<div class="admin-panel">

<h4>Imagenes registradas</h4>

<div class="row">
	@foreach($imagenes as $imagen)

	<div class="col-md-4">
		
		<div class="panel panel-default">
			<div class="panel-body">
				<img src="{{url('/images/cursos/')}}/{{ $imagen->nombre }}" class="img-responsive">
			</div>
			<div class="panel-footer">{{$imagen->curso->nombre}}</div>
		</div>

	</div>

	@endforeach
</div>
			
</div>
			<div class="text-center" >{!!$imagenes->links()!!}</div>
</div>

@endsection

@section('footer')

@include('partials.footer')

@endsection