routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','FrontController@index');

Route::get('/perfil/{nombre}', [

	'uses' => 'FrontController@perfil',

	'as' => 'usuario.perfil'


	]);

Route::put('/perfil/{nombre}', [

	'uses' => 'FrontController@perfil_update',

	'as' => 'usuario.update'

	]);

Route::get('/cursos','FrontController@cursos');

Route::group(['prefix' => 'cursos'], function () {

Route::get('/categorias/{nombre}',[


	'uses' => 'FrontController@buscarCategoria', 
	'as' => 'buscar.categoria'

	]);

Route::get('/autor/{name}',[

	'uses' => 'FrontController@buscarAutores',
	'as' => 'buscar.autores'


	]);



});


Route::get('/cursos/{slug}',[

	'uses' => 'FrontController@contenido',
	'as' => 'curso.contenido'

	]);

Route::get('/politicas','FrontController@politicas');

Route::get('/terminos','FrontController@terminos');



Auth::routes();


Route::get('/home', 'HomeController@index');

//RUTAS DE ADMINISTRADOR

Route::group(['prefix' => 'administrador', 'middleware' => 'auth'], function () {

//-->AQUI SE PUEDEN COLOCAR RUTAS DE ACCCESO ADMINISTRATIVO PARA USUARIOS MIEMBRO

	Route::group(['middleware'=>'administrador'], function() {

					Route::resource('usuarios','UsuariosController');

					Route::get('/usuarios/{id}/destroy',[

						'uses' => 'UsuariosController@destroy',
						'as'   => 'administrador.usuarios.destroy'

						]);
					Route::resource('categorias','CategoriasController');

					Route::get('/categorias/{id}/destroy',[

						'uses' => 'CategoriasController@destroy',
						'as'   => 'administrador.categorias.destroy'

						]);

					Route::resource('tags','TagsController');

					Route::get('/tags/{id}/destroy',[

						'uses' => 'TagsController@destroy',
						'as'   => 'administrador.tags.destroy'

						]);

					Route::resource('/cursos','CursosController');

					Route::get('/cursos/{id}/destroy',[

						'uses' => 'CursosController@destroy',
						'as'   => 'administrador.cursos.destroy'

						]);

					Route::get('/imagenes',[

						'uses' => 'ImagenesController@index',
						'as'   => 'administrador.imagenes.index'

						]);

			Route::group(['prefix' => 'curso/{id_curso}'], function () {

					Route::resource('/contenidos','ContenidosController');

					Route::get('/contenidos/{id_contenido}/destroy',[

						'uses' => 'ContenidosController@destroy',
						'as'   => 'administrador.contenidos.destroy'

						]);

								Route::group(['prefix' => 'contenido/{id_contenido}'], function () {

											Route::resource('/capitulos','CapitulosController');

											Route::get('/capitulos/{id_capitulo}/destroy',[

											'uses' => 'CapitulosController@destroy',
											'as'   => 'administrador.capitulos.destroy'

									]);

				});

				});

	});



});

app/Contenido.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contenido extends Model
{
    
    protected $table = "contenidos";
    protected $fillable = ['titulo','curso_id'];

        public function curso() {

    	return $this->belongsTo('App\Curso','curso_id');
    }

       public function scopeBuscarContenido ($query, $curso_id) {

    	return $query->where('curso_id','=',$curso_id);
    }

            public function capitulos () {

        return $this->hasMany('App\Capitulo','contenido_id');
    }

}

app/Http/Controllers/ContenidosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Contenido;
use Laracasts\Flash\Flash;
use App\Http\Requests\ContenidoRequest;

class ContenidosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($curso_id)
    {
        $contenidos = Contenido::BuscarContenido($curso_id)->orderBy('id','ASC')->paginate(10);



        return view('administrador.contenidos.index',['contenidos' => $contenidos,'curso_id' => $curso_id]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($curso_id)
    {

        return view('administrador.contenidos.create',['curso_id' => $curso_id]);
           
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContenidoRequest $request,$curso_id)
    {
        $contenido  = new Contenido($request->all());
        $contenido->curso_id = $curso_id;
        
         if($contenido->save()) {

        Flash::success("Se ha registrado el contenido: ". $contenido->titulo . " Exitosamente¡¡");
        return redirect()->route('contenidos.index',$curso_id);
       
       }else{
        Flash::error("No se pudo crear el contenido");
        return redirect()->route('contenidos.create',$curso_id);
       }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id_curso,$id_contenido)
    {
        $contenido = Contenido::find($id_contenido);
      

        return view('administrador.contenidos.edit',['contenido' => $contenido]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $curso_id,$contenido_id)
    {
        $contenido = Contenido::find($contenido_id);
        $contenido->fill($request->all());

        if($contenido->save()) {

      
        Flash::success("Se ha actualizado el contenido : ". $contenido->titulo . " Exitosamente¡¡");
         return redirect()->route('contenidos.index',$curso_id);
       
       }else{
        Flash::error("No se pudo actualizar el contenido");
        return redirect()->route('contenidos.edit',[$curso_id,$contenido_id]);
       }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($curso_id,$contenido_id)
    {
        $contenido = Contenido::find($contenido_id);
        
        if($contenido->delete()) {

        Flash::success("Contenido: " . $contenido->titulo . " Eliminado Exitosamente¡¡");
          return redirect()->route('contenidos.index',$curso_id);   
       
       }else{
        Flash::error('No se pudo eliminar el curso');
           return redirect()->route('contenidos.index',$curso_id); 
       }
    }
}

resources/views/administrador/contenidos/create.blade.php
@extends('layouts.app')

@section('title','Crear Categoria')

@section('header')

@include('partials.header')

@endsection

@section('content')


<div class="view-school">

		<section id="breadcrumbs-container">
			<div class="container">
				<div class="row">
					<div class="col-xs">
						<nav class="breadcrumb">

							<a href="{{route('cursos.index')}}" class="breadcrumb-item">Cursos</a>
							<a href="{{route('contenidos.index',$curso_id)}}" class="breadcrumb-item">/ Contenidos</a>
							<span class="breadcrumb-item active">/ Creacion de contenidos</span>
						</nav>
					</div>
				</div>
			</div>
		</section>

<div class="admin-panel">

<h4>Crear nuevo contenido</h4>

{!!Form::open(['route' => ['contenidos.store',$curso_id], 'method' => 'POST'])!!}

<div class="form-group">
	{!!Form::label('titulo','Titulo del contenido')!!}
	{!!Form::text('titulo', null, ['class' => 'form-control', 'placeholder'=> 'Titulo del contenido' ,'required'])!!}
</div>


<div class="form-group text-center">
	{!!Form::submit('Registrar', ['class' => 'btn btn-primary '])!!}
</div>

{!!Form::close()!!}

</div>
</div>

@endsection

@section('footer')

@include('partials.footer')

@endsection

resources/views/administrador/contenidos/edit.blade.php
@extends('layouts.app')

@section('title','Editar Contenido')

@section('header')

@include('partials.header')

@endsection

@section('content')


<div class="view-school">

		<section id="breadcrumbs-container">
			<div class="container">
				<div class="row">
					<div class="col-xs">
						<nav class="breadcrumb">

							<a href="{{route('cursos.index')}}" class="breadcrumb-item">Cursos</a>
							<a href="{{route('contenidos.index',$contenido->curso_id)}}" class="breadcrumb-item">/ Contenidos</a>
							<span class="breadcrumb-item active">/ Edicion de contenidos</span>
						</nav>
					</div>
				</div>
			</div>
		</section>

<div class="admin-panel">

<h4>Editar Contenido: ("{{$contenido->titulo}}")</h4>

{!!Form::open(['route' => ['contenidos.update',$contenido->curso_id,$contenido->id], 'method' => 'PUT'])!!}

<div class="form-group">
	{!!Form::label('titulo','Titulo del contenido')!!}
	{!!Form::text('titulo', $contenido->titulo, ['class' => 'form-control', 'placeholder'=> 'Titulo del contenido' ,'required'])!!}
</div>


<div class="form-group text-center">
	{!!Form::submit('Editar', ['class' => 'btn btn-primary '])!!}
</div>

{!!Form::close()!!}

</div>
</div>

@endsection

@section('footer')

@include('partials.footer')

@endsection

resources/views/administrador/contenidos/index.blade.php
@extends('layouts.app')

@section('title','Contenidos')

@section('header')

@include('partials.header')

@endsection

@section('content')

<div class="view-school">

		<section id="breadcrumbs-container">
			<div class="container">
				<div class="row">
					<div class="col-xs">
						<nav class="breadcrumb">

							<a href="{{route('cursos.index')}}" class="breadcrumb-item">Cursos</a>
							<span class="breadcrumb-item active">/ Contenido del curso</span>
						</nav>
					</div>
				</div>
			</div>
		</section>

<div class="admin-panel">

<h4>Contenido del curso</h4>

<table class="table table-striped">	
		<thead>
			<th>ID</th>
			<th>Titulo del Contenido</th>
			<th>Accion</th>
		</thead>
		<tbody>
			@foreach($contenidos as $contenido)
				<tr>
					<td>{{$contenido->id}}</td>
					<td><a href="{{route('capitulos.index',[$contenido->curso_id,$contenido->id])}}">{{$contenido->titulo}}</a></td>
					<td>
						<a class="btn btn-warning" href="{{route('contenidos.edit',[$contenido->curso_id,$contenido->id])}}"><i class="fa fa-pencil-square" aria-hidden="true"></i></a>
						<a class="btn btn-danger" href="{{route('administrador.contenidos.destroy',[$contenido->curso_id,$contenido->id])}}" onclick="return confirm('¿Seguro que deeas Eliminar este usuario')"><i class="fa fa-trash" aria-hidden="true"></i></a>

					</td>
				</tr>
			@endforeach
		</tbody>
</table>

				<a class="btn btn-primary" href="{{route('contenidos.create',[$curso_id])}}">Crear nuevo contenido</a>

			<div class="text-center" >{!!$contenidos->links()!!}</div>
</div>
</div>


@endsection

@section('footer')

@include('partials.footer')

@endsection